config/routes.rb
Rails.application.routes.draw do

  resources :dinner_orders

  resources :lunch_orders

  resources :breakfast_orders

  resources :menu_contents
  resources :foods
  resources :days

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  resource :home
  resource :dashboard

  root 'homes#show'

end

app/models/lunch_order.rb
class LunchOrder < ActiveRecord::Base
  belongs_to :user
  belongs_to :menu_content
  has_many :foods, through: :menu_content, class_name: 'Food'
end

app/controllers/lunch_orders_controller.rb
class LunchOrdersController < ApplicationController
  before_action :set_lunch_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @lunch_orders = LunchOrder.where(user_id: current_user.id).limit(26).order(created_at: :desc)
    respond_with(@lunch_orders)
  end

  def show
    respond_with(@lunch_order)
  end

  def new
    @lunch_order = LunchOrder.new
    respond_with(@lunch_order)
  end

  def edit
  end

  def create
    @lunch_order = LunchOrder.new(lunch_order_params)
    respond_to do |format|
      if @lunch_order.save
        format.html do
          redirect_to lunch_orders_path,
                      notice: 'You have successfully ordered lunch.'
        end
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @lunch_order.update(lunch_order_params)
        format.html do
          redirect_to lunch_orders_path,
                      notice: 'You have successfully updated your lunch order.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @lunch_order.destroy
        format.html do
          redirect_to lunch_orders_path,
                      notice: 'You have successfully deleted your lunch order.'
        end
      else
        format.html { render :index }
      end
    end
  end

  private
    def set_lunch_order
      @lunch_order = LunchOrder.find(params[:id])
    end

    def lunch_order_params
      params.require(:lunch_order).permit(:user_id, :menu_content_id)
    end
end

app/helpers/lunch_orders_helper.rb
module LunchOrdersHelper
end

app/views/lunch_orders/_form.html.erb
<%= form_for(@lunch_order) do |f| %>
  <% if @lunch_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch_order.errors.count, "error") %> prohibited this lunch order from being saved:</h2>

      <ul>
      <% @lunch_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= hidden_field(:lunch_order, :user_id, value: current_user.id)%>
    </div>
    <div class="field">
      <%= f.label :menu_content_id %><br>
      <%= f.collection_select :menu_content_id, MenuContent.where({ day_id: Time.now.wday, occasion: "Lunch" }).order(:id), :id, :food_item,
                              :include_blank => true
      %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunch_orders/edit.html.erb
<h1 class="page-header">Edit Lunch Order</h1>

<%= render 'form' %>

<%= link_to 'Back', lunch_orders_path %>

app/views/lunch_orders/index.html.erb
<h1 class="page-header">My Lunch Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lunch_orders.each do |lunch_order| %>
      <tr>
        <td><%= lunch_order.menu_content.food_item %> |</td>
        <td><%= link_to 'Edit', edit_lunch_order_path(lunch_order) %> |</td>
        <td><%= link_to 'Destroy', lunch_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lunch order', new_lunch_order_path %>

app/views/lunch_orders/new.html.erb
<h1 class="page-header">New Lunch Order</h1>

<%= render 'form' %>

<%= link_to 'Back', lunch_orders_path %>