config/routes.rb
Rails.application.routes.draw do

  resources :dinner_orders

  resources :lunch_orders

  resources :breakfast_orders

  resources :menu_contents
  resources :foods
  resources :days

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  resource :home
  resource :dashboard

  root 'homes#show'

end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :menu_contents
  has_many :foods, through: :menu_content, class_name: 'Food'
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_admin?

  def is_admin?
    if current_user.admin?
      true
    else
      redirect_to root_path
    end
  end

  respond_to :html

  def index
    @days = Day.all
    respond_with(@days)
  end

  def show
    respond_with(@day)
  end

  def new
    @day = Day.new
    respond_with(@day)
  end

  def edit
  end

  def create
    @user_admin = current_user.admin?
    if @user_admi
      @day = Day.new(day_params)
      @day.save
      respond_with(@day)
    else
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/401.html", status: 401, layout: false }
      end
    end
  end

  def update
    @user_admin = current_user.admin?
    if @user_admi
      @day.update(day_params)
      respond_with(@day)
    else
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/401.html", status: 401, layout: false }
      end
    end
  end

  def destroy
    @user_admin = current_user.admin?
    if @user_admi
      @day.destroy
      respond_with(@day)
    else
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/401.html", status: 401, layout: false }
      end
    end
  end

  private
    def set_day
      @day = Day.find(params[:id])
    end

    def day_params
      params.require(:day).permit(:day)
    end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= day.day %></td>
        <td><%= link_to 'Show', day %></td>
        <td><%= link_to 'Edit', edit_day_path(day) %></td>
        <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.try(:admin?) %>
  <%= link_to 'New Day', new_day_path %>
<% end %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @day.day %>
</p>

<%= link_to 'Back', days_path %> |