config/routes.rb
Rails.application.routes.draw do

  resources :dinner_orders

  resources :lunch_orders

  resources :breakfast_orders

  resources :menu_contents
  resources :foods
  resources :days

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  resource :home
  resource :dashboard

  root 'homes#show'

end

app/models/breakfast_order.rb
class BreakfastOrder < ActiveRecord::Base
  belongs_to :user
  belongs_to :menu_content
  has_many :foods, through: :menu_content, class_name: 'Food'
end

app/controllers/breakfast_orders_controller.rb
class BreakfastOrdersController < ApplicationController
  before_action :set_breakfast_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @breakfast_orders = BreakfastOrder.where(user_id: current_user.id).limit(26).order(created_at: :desc)
    respond_with(@breakfast_orders)
  end

  def show
    respond_with(@breakfast_order)
  end

  def new
    @breakfast_order = BreakfastOrder.new
    respond_with(@breakfast_order)
  end

  def edit
  end

  def create
    @breakfast_order = BreakfastOrder.new(breakfast_order_params)
    respond_to do |format|
      if @breakfast_order.save
        format.html do
          redirect_to breakfast_orders_path,
                      notice: 'You have successfully ordered breakfast.'
        end
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @breakfast_order.update(breakfast_order_params)
        format.html do
          redirect_to breakfast_orders_path,
                      notice: 'You have successfully updated your breakfast order.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @breakfast_order.destroy
        format.html do
          redirect_to breakfast_orders_path,
                      notice: 'You have successfully deleted your breakfast order.'
        end
      else
        format.html { render :index }
      end
    end
  end

  private
    def set_breakfast_order
      @breakfast_order = BreakfastOrder.find(params[:id])
    end

    def breakfast_order_params
      params.require(:breakfast_order).permit(:user_id, :menu_content_id)
    end
end

app/helpers/breakfast_orders_helper.rb
module BreakfastOrdersHelper
end

app/views/breakfast_orders/_form.html.erb
<%= form_for(@breakfast_order) do |f| %>
    <% if @breakfast_order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@breakfast_order.errors.count, "error") %> prohibited this breakfast order from being saved:</h2>

          <ul>
            <% @breakfast_order.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= hidden_field(:breakfast_order, :user_id, value: current_user.id)%>
    </div>
    <div class="field">
      <%= f.label :menu_content_id %><br>
      <%= f.collection_select :menu_content_id, MenuContent.where({ day_id: Time.now.wday, occasion: "Breakfast" }).order(:id), :id, :food_item,
                              :include_blank => true
      %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/breakfast_orders/edit.html.erb
<h1 class="page-header">Edit Breakfast Order</h1>

<%= render 'form' %>

<%= link_to 'Back', breakfast_orders_path %>

app/views/breakfast_orders/index.html.erb
<h1 class="page-header">My Breakfast Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breakfast_orders.each do |breakfast_order| %>
      <tr>
        <td><%= breakfast_order.menu_content.food_item %> |</td>
        <td><%= breakfast_order.menu_content.day.day %> |</td>
        <td><%= link_to 'Edit', edit_breakfast_order_path(breakfast_order), class: '' %> |</td>
        <td><%= link_to 'Destroy', breakfast_order, method: :delete, data: { confirm: 'Are you sure?' }, class: '' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Breakfast order', new_breakfast_order_path %>

app/views/breakfast_orders/new.html.erb
<h1 class="page-header">New Breakfast Order</h1>

<%= render 'form' %>

<%= link_to 'Back', breakfast_orders_path %>