config/routes.rb
Rails.application.routes.draw do

  resources :dinner_orders

  resources :lunch_orders

  resources :breakfast_orders

  resources :menu_contents
  resources :foods
  resources :days

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  resource :home
  resource :dashboard

  root 'homes#show'

end

app/models/breakfast_order.rb
class BreakfastOrder < ActiveRecord::Base
  belongs_to :user
  belongs_to :menu_content
  has_many :foods, through: :menu_content, class_name: 'Food'
end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :menu_contents
  has_many :foods, through: :menu_content, class_name: 'Food'
end

app/models/dinner_order.rb
class DinnerOrder < ActiveRecord::Base
  belongs_to :user
  belongs_to :menu_content
  has_many :foods, through: :menu_content, class_name: 'Food'
end

app/models/food.rb
class Food < ActiveRecord::Base
  belongs_to :menu_content
end

app/models/lunch_order.rb
class LunchOrder < ActiveRecord::Base
  belongs_to :user
  belongs_to :menu_content
  has_many :foods, through: :menu_content, class_name: 'Food'
end

app/models/menu_content.rb
class MenuContent < ActiveRecord::Base
  belongs_to :day
  belongs_to :food
  belongs_to :breakfast_order
  belongs_to :lunch_order
  belongs_to :dinner_order

  validates :day_id, presence: true, numericality: true
  validates :food_id, presence: true, numericality: true

  OCCASION = ['Breakfast', 'Lunch', 'Dinner']

  def food_item
    food.item
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :breakfast_orders
  has_many :lunch_orders
  has_many :dinner_orders
  has_many :foods, through: :menu_content, class_name: 'Food'
  devise :omniauthable, :omniauth_providers => [:google_oauth2]

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(provider: access_token.provider, uid: access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
                           provider:access_token.provider,
                           email: data["email"],
                           image: data["image"],
                           uid: access_token.uid ,
                           password: Devise.friendly_token[0,20],
        )
      end
    end
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_admin?

  def is_admin?
    if current_user.admin?
      true
    else
      redirect_to root_path
    end
  end


  def show
    @breakfast_orders = BreakfastOrder.where('created_at.wday'== 'Time.now.wday')
    @lunch_orders = LunchOrder.where('created_at.wday'== 'Time.now.wday')
    @dinner_orders = DinnerOrder.where('created_at.wday'== 'Time.now.wday')
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_admin?

  def is_admin?
    if current_user.admin?
      true
    else
      redirect_to root_path
    end
  end

  respond_to :html

  def index
    @days = Day.all
    respond_with(@days)
  end

  def show
    respond_with(@day)
  end

  def new
    @day = Day.new
    respond_with(@day)
  end

  def edit
  end

  def create
    @user_admin = current_user.admin?
    if @user_admi
      @day = Day.new(day_params)
      @day.save
      respond_with(@day)
    else
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/401.html", status: 401, layout: false }
      end
    end
  end

  def update
    @user_admin = current_user.admin?
    if @user_admi
      @day.update(day_params)
      respond_with(@day)
    else
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/401.html", status: 401, layout: false }
      end
    end
  end

  def destroy
    @user_admin = current_user.admin?
    if @user_admi
      @day.destroy
      respond_with(@day)
    else
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/401.html", status: 401, layout: false }
      end
    end
  end

  private
    def set_day
      @day = Day.find(params[:id])
    end

    def day_params
      params.require(:day).permit(:day)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :is_admin?

  def is_admin?
    if current_user.admin?
      true
    else
      redirect_to root_path
    end
  end

  respond_to :html

  def index
    @foods = Food.all
    respond_with(@foods)
  end

  def show
    respond_with(@food)
  end

  def new
    @food = Food.new
    respond_with(@food)
  end

  def edit
  end

  def create
    @user_admin = current_user.admin?
    if @user_admin
      @food = Food.new(food_params)
      respond_to do |format|
        if @food.save
          format.html do
            redirect_to foods_path,
                        notice: 'Food was successfully created.'
          end
        else
          format.html { render :new }
        end
      end
    else
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/401.html", status: 401, layout: false }
      end
    end
  end

  def update
    @user_admin = current_user.admin?
    if @user_admin
      respond_to do |format|
        if @food.update(food_params)
          format.html do
            redirect_to foods_path,
                        notice: 'Food was successfully updated.'
          end
        else
          format.html { render :new }
        end
      end
    else
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/401.html", status: 401, layout: false }
      end
    end
  end

  def destroy
    @user_admin = current_user.admin?
    if @user_admin
      @food.destroy
      respond_with(@food)
    else
      respond_to do |format|
        format.html { render file: "#{Rails.root}/public/401.html", status: 401, layout: false }
      end
    end
  end

  private
    def set_food
      @food = Food.find(params[:id])
    end

    def food_params
      params.require(:food).permit(:item)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    # @ip = request.remote_ip
    # @ip2 = Socket.ip_address_list.find { |ai| ai.ipv4? && !ai.ipv4_loopback? }.ip_address
    # @location = Geocoder::Result.location
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breakfast_orders_helper.rb
module BreakfastOrdersHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/dinner_orders_helper.rb
module DinnerOrdersHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lunch_orders_helper.rb
module LunchOrdersHelper
end

app/helpers/menu_contents_helper.rb
module MenuContentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="col-md-8">
  <div class="row">
    <div class="col-md-6">
      <%= link_to(image_tag("Logo.png", alt: "Andela Logo", width: '250', height: '55', class: "logo", title: "Andela"),root_path ) %>
    </div>
    <% if user_signed_in? %>
     <div class="col-md-6"><%= image_tag (current_user.image), class:"avatar pull-right" %></div>
    <% end %>
  </div>
</nav>
<div class="current-user col-md-3 pull-right text-center">
  <% if user_signed_in? %>
      <div class="row">
          <strong><%= current_user.name %></strong>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-default" %>
      </div>
      <hr>
      <%= link_to "My Breakfast Orders", breakfast_orders_path, class: "button" %>
      <hr>
      <%= link_to "My Lunch Orders", lunch_orders_path, class: "button" %>
      <hr>
      <%= link_to "My Dinner Orders", dinner_orders_path, class: "button" %>
      <hr>
      <%= link_to "Available Today", menu_contents_path, class: "button" %>
      <hr>
  <% else %>
      <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), class: "btn btn-default" %>
      <%= link_to "Admin", new_user_session_path, class: "btn btn-default" %>
<% end %>
  <p class="date"><%= Time.now.to_date %></p>
</div>
<div class="admin-tasks">
  <% if current_user.try(:admin?) %>
    <%= link_to "All foods", foods_path, class: "btn btn-default" %>
    <%= link_to "Days", days_path, class: "btn btn-default" %>
    <%= link_to "All Orders", dashboard_path, class: "btn btn-default" %>
  <% end %>
  <%= link_to "Settings", edit_user_registration_path, class: "btn btn-default" %>
</div>
<div class="content-container">
  <%= yield %>
</div>

</body>
</html>